TARGET = ReplicateNullModel
OBJECTS_DIR = build
MOC_DIR = build
UI_DIR = build
CONFIG += qt
CONFIG += debug
RESOURCES = ./src/gui/gui.qrc
QT += qml quick widgets core

SOURCES += aboutdialog.cpp
SOURCES += main.cpp
SOURCES += ./src/app/core/gradientshader.cpp
SOURCES += ./src/app/core/localitycollection.cpp
SOURCES += ./src/app/core/localitylist.cpp
SOURCES += ./src/app/core/raster.cpp
SOURCES += ./src/app/core/rastermodel.cpp
SOURCES += ./src/app/core/specieslocalityset.cpp
SOURCES += ./src/app/nullmodeltest/binomialtest.cpp
SOURCES += ./src/app/nullmodeltest/calibrationtest.cpp
SOURCES += ./src/app/nullmodeltest/landscapemapper.cpp
SOURCES += ./src/app/nullmodeltest/pyramidtemplatetest.cpp
SOURCES += ./src/app/nullmodeltest/randomdistributiontest.cpp
SOURCES += ./src/app/nullmodeltest/randomtranslationrotationtest.cpp
SOURCES += ./src/app/nullmodeltest/randomtranslationrotationthread.cpp
SOURCES += ./src/app/nullmodeltest/replicaterelabeler.cpp
SOURCES += ./src/app/nullmodeltest/replicatenullmodeltest.cpp
SOURCES += ./src/app/nullmodeltest/replicatenullmodeltestthread.cpp
SOURCES += ./src/app/nullmodeltest/replicatetemplate.cpp
SOURCES += ./src/app/nullmodeltest/statisticsengine.cpp
SOURCES += ./src/app/nullmodeltest/templatetestthread.cpp
SOURCES += ./src/gui/colorstopframe.cpp
SOURCES += ./src/gui/localitiestablewidget.cpp
SOURCES += ./src/gui/rastergraphicsview.cpp
SOURCES += ./src/gui/rasterviewer.cpp
SOURCES += ./src/gui/replicatenullmodelwindow.cpp
SOURCES += ./src/gui/replicatenullmodelconfigdialog.cpp
SOURCES += ./src/gui/tablewidget.cpp

HEADERS += aboutdialog.h
HEADERS += ./src/app/core/gradientshader.h
HEADERS += ./src/app/core/locality.h
HEADERS += ./src/app/core/localitycollection.h
HEADERS += ./src/app/core/localitylist.h
HEADERS += ./src/app/core/raster.h
HEADERS += ./src/app/core/rastermodel.h
HEADERS += ./src/app/core/specieslocalityset.h
HEADERS += ./src/app/nullmodeltest/binomialtest.h
HEADERS += ./src/app/nullmodeltest/binomialtestresult.h
HEADERS += ./src/app/nullmodeltest/calibrationtest.h
HEADERS += ./src/app/nullmodeltest/landscapemapper.h
HEADERS += ./src/app/nullmodeltest/replicaterelabeler.h
HEADERS += ./src/app/nullmodeltest/probability.h
HEADERS += ./src/app/nullmodeltest/pyramidtemplatetest.h
HEADERS += ./src/app/nullmodeltest/randomdistributiontest.h
HEADERS += ./src/app/nullmodeltest/randomtranslationrotationtest.h
HEADERS += ./src/app/nullmodeltest/randomtranslationrotationthread.h
HEADERS += ./src/app/nullmodeltest/replicatenullmodeltest.h
HEADERS += ./src/app/nullmodeltest/replicatenullmodeltestthread.h
HEADERS += ./src/app/nullmodeltest/replicatetemplate.h
HEADERS += ./src/app/nullmodeltest/statisticsengine.h
HEADERS += ./src/app/nullmodeltest/templatetestthread.h
HEADERS += ./src/gui/colorstopframe.h
HEADERS += ./src/gui/localitiestablewidget.h
HEADERS += ./src/gui/rastergraphicsview.h
HEADERS += ./src/gui/rasterviewer.h
HEADERS += ./src/gui/replicatenullmodelwindow.h
HEADERS += ./src/gui/replicatenullmodelconfigdialog.h
HEADERS += ./src/gui/tablewidget.h

FORMS += aboutdialog.ui
FORMS += ./src/ui/rasterviewerwidget.ui
FORMS += ./src/ui/replicatenullmodelconfigdialog.ui
FORMS += ./src/ui/replicatenullmodelwindow.ui

INCLUDEPATH = ./ ./src/app ./src/app/core ./src/app/nullmodeltest ./src/gui/
#Quote if spaces $$quote(/usr/include/gdal)
unix:INCLUDEPATH += /usr/include/gdal /usr/include/
win32:INCLUDEPATH += C:/OSGeo4W/include C:/OSGeo4W/boost_1_50_0 C:/OSGeo4W/gsl C:/OSGeo4W/bin

unix:LIBS += -L/usr/lib/ -lgdal -lgsl -l gslcblas
win32:LIBS = -LC:/OSGeo4W/lib -lgdal_i
